apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: grafana.rules
  namespace: {{ .Values.namespace }}
spec:
  groups:
  - name: grafana
    rules:
    - alert: GrafanaDown
      annotations:
        description: '{{`Grafana ({{ $labels.instance }}) is down.`}}'
        runbook_url: '{{`https://intranet.giantswarm.io/docs/support-and-ops/runbooks/grafana/?INSTALLATION={{ $labels.installation }}&CLUSTER={{ $labels.cluster_id }}`}}'
        __dashboardUid__: qRQXmRnik
        dashboardQueryParams: "orgId=2"
      expr: up{service="grafana", cluster_type="management_cluster"} == 0
      for: 1h
      labels:
        area: platform
        cancel_if_outside_working_hours: "true"
        severity: page
        team: atlas
        topic: observability
    - alert: GrafanaPostgresqlReplicationFailure
      annotations:
        description: '{{`grafana-postgresql replication is lagging for pod {{ $labels.pod }}.`}}'
        runbook_url: '{{`https://intranet.giantswarm.io/docs/support-and-ops/runbooks/grafana/?INSTALLATION={{ $labels.installation }}&CLUSTER={{ $labels.cluster_id }}`}}'
      expr: sum(cnpg_pg_replication_lag{namespace="monitoring", pod=~"grafana-postgresql.*"}) by (pod, cluster_id, installation, pipeline, provider) > 300
      for: 10m
      labels:
        area: platform
        cancel_if_outside_working_hours: "true"
        severity: page
        team: atlas
        topic: observability
    - alert: GrafanaPostgresqlArchivingFailure
      annotations:
        description: '{{`grafana-postgresql archiving failed for pod {{ $labels.pod }}.`}}'
        runbook_url: '{{`https://intranet.giantswarm.io/docs/support-and-ops/runbooks/grafana/?INSTALLATION={{ $labels.installation }}&CLUSTER={{ $labels.cluster_id }}`}}'
      expr: sum((cnpg_pg_stat_archiver_last_failed_time{namespace="monitoring", pod=~"grafana-postgresql.*"} - cnpg_pg_stat_archiver_last_archived_time{namespace="monitoring", pod=~"grafana-postgresql.*"})) by (pod, cluster_id, installation, pipeline, provider) > 1
      for: 5m
      labels:
        area: platform
        cancel_if_outside_working_hours: "true"
        severity: page
        team: atlas
        topic: observability
    - alert: GrafanaPostgresqlRecoveryTestFailed
      annotations:
        description: '{{`grafana-postgresql db automated recovery test failed.`}}'
        runbook_url: '{{`https://intranet.giantswarm.io/docs/support-and-ops/runbooks/grafana/?INSTALLATION={{ $labels.installation }}&CLUSTER={{ $labels.cluster_id }}`}}'
      # Fires when all existing grafana-postgresql recovery test Jobs have failed. Clears as soon as a new Job succeeds.
      expr: |
        min by (cluster_id, installation, pipeline, provider) (
          kube_job_failed{job_name=~"grafana-postgresql-recovery-test.+", namespace="monitoring", condition="true"}
        ) == 1
      for: 1d
      labels:
        area: platform
        cancel_if_outside_working_hours: "true"
        severity: page
        team: atlas
        topic: observability
