apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: kafka-bridge.rules
  namespace: {{ .Values.namespace  }}
spec:
  groups:
    - name: kafka-bridge
      rules:
        - alert: KafkaBridgeAvgProducerLatency
          expr: strimzi_bridge_kafka_producer_request_latency_avg > 10
          for: 3m
          labels:
            area: platform
            severity: none
            team: atlas
            topic: kafka
          annotations:
            summary: 'Kafka Bridge producer average request latency'
            description: '{{`The average producer request latency is {{ $value }} on {{ $labels.clientId }}`}}'
        - alert: KafkaBridgeAvgConsumerFetchLatency
          expr: strimzi_bridge_kafka_consumer_fetch_latency_avg > 500
          for: 3m
          labels:
            area: platform
            severity: none
            team: atlas
            topic: kafka
          annotations:
            summary: 'Kafka Bridge consumer average fetch latency'
            description: '{{`The average consumer fetch latency is {{ $value }} on {{ $labels.clientId }}`}}'
        - alert: KafkaBridgeAvgConsumerCommitLatency
          expr: strimzi_bridge_kafka_consumer_commit_latency_avg > 200
          for: 3m
          labels:
            area: platform
            severity: none
            team: atlas
            topic: kafka
          annotations:
            summary: 'Kafka Bridge consumer average commit latency'
            description: '{{`The average consumer commit latency is {{ $value }} on {{ $labels.clientId }}`}}'
        - alert: KafkaBridgeHttp4xxErrorRate
          expr: sum by (cluster_id, installation, pipeline, provider, namespace, pod, path) (increase(strimzi_bridge_http_server_requests_total{code=~"4..", container=~".+-bridge", path!="/favicon.ico"}[5m])) > 10
          for: 1m
          labels:
            area: platform
            severity: none
            team: atlas
            topic: kafka
          annotations:
            summary: 'Kafka Bridge returns code 4xx too often'
            description: '{{`Kafka Bridge returns code 4xx too much ({{ $value }}) for the path {{ $labels.path }}`}}'
        - alert: KafkaBridgeHttp5xxErrorRate
          expr: sum by (cluster_id, installation, pipeline, provider, namespace, pod, path) (increase(strimzi_bridge_http_server_requests_total{code=~"5..", container=~".+-bridge", path!="/favicon.ico"}[5m])) > 10
          for: 1m
          labels:
            area: platform
            severity: none
            team: atlas
            topic: kafka
          annotations:
            summary: 'Kafka Bridge returns code 5xx too often'
            description: '{{`Kafka Bridge returns code 5xx too much ({{ $value }}) for the path {{ $labels.path }}`}}'
