apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: kafka-exporter.rules
  namespace: {{ .Values.namespace  }}
spec:
  groups:
    - name: kafka-exporter
      rules:
        - alert: KafkaExporterUnderReplicatedPartition
          expr: kafka_topic_partition_under_replicated_partition > 0
          for: 10m
          labels:
            area: platform
            severity: none
            team: atlas
          annotations:
            summary: 'Topic has under-replicated partitions'
            description: '{{`Topic  {{ $labels.topic }} has {{ $value }} under-replicated partition {{ $labels.partition }}`}}'
        - alert: KafkaExporterTooLargeConsumerGroupLag
          expr: kafka_consumergroup_lag > 1000
          for: 15m
          labels:
            area: platform
            severity: none
            team: atlas
          annotations:
            summary: 'Consumer group lag is too big'
            description: '{{`Consumer group {{ $labels.consumergroup}} lag is too big ({{ $value }}) on topic {{ $labels.topic }}/partition {{ $labels.partition }}`}}'
        - alert: KafkaExporterNoMessageForTooLong
          expr: changes(kafka_topic_partition_current_offset[10m]) == 0
          for: 10s
          labels:
            area: platform
            severity: none
            team: atlas
          annotations:
            summary: 'No message for 10 minutes'
            description: '{{`There is no messages in topic {{ $labels.topic}}/partition {{ $labels.partition }} for 10 minutes`}}'
