apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: kafka-connect.rules
  namespace: {{ .Values.namespace  }}
spec:
  groups:
    - name: kafka-connect
      rules:
        - alert: KafkaConnectContainersDown
          expr: absent(container_last_seen{container=~".+-connect",pod=~".+-connect-.+"})
          for: 3m
          labels:
            area: platform
            severity: none
            team: atlas
            topic: kafka
          annotations:
            summary: 'All Kafka Connect containers down or in CrashLookBackOff status'
            description: 'All Kafka Connect containers have been down or in CrashLookBackOff status for 3 minutes'
        - alert: KafkaConnectFailedConnector
          expr: sum(kafka_connect_connector_status{status="failed"}) by (cluster_id, installation, pipeline, provider, namespace, pod) > 0
          for: 5m
          labels:
            area: platform
            severity: none
            team: atlas
            topic: kafka
          annotations:
            summary: 'Kafka Connect Connector Failure'
            description: '{{`Kafka instance on pod {{ $labels.namespace }}/{{ $labels.pod }} has {{ $value }} connector(s) in failed state during last 5 minutes`}}'
        - alert: KafkaConnectFailedTask
          expr: sum(kafka_connect_worker_connector_failed_task_count) by (cluster_id, installation, pipeline, provider, namespace, pod) > 0
          for: 5m
          labels:
            area: platform
            severity: none
            team: atlas
            topic: kafka
          annotations:
            summary: 'Kafka Connect Task Failure'
            description: '{{`Kafka instance on pod {{ $labels.namespace }}/{{ $labels.pod }} has {{ $value }} task(s) in failed state during last 5 minutes`}}'
