apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: kafka-certificate.rules
  namespace: {{ .Values.namespace  }}
spec:
  groups:
    - name: kafka-certificate
      interval: 1m0s
      rules:
        - alert: KafkaCertificateExpiration
          expr: |
            strimzi_certificate_expiration_timestamp_ms/1000 - time() < 30 * 24 * 60 * 60
          for: 5m
          labels:
            area: platform
            severity: none
            team: atlas
            topic: kafka
          annotations:
            summary: 'Certificate will expire in less than 30 days'
            description: '{{`Certificate of type {{ $labels.type }} in cluster {{ $labels.cluster }} in namespace {{ $labels.resource_namespace }} will expire in less than 30 days`}}'
