apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: kafka-exporter.rules
  namespace: {{ .Values.namespace  }}
spec:
  groups:
    - name: kafka-exporter-topic
      rules:
        # `topic` is dropped from alert labels here because it collides with the Kafka `topic` label on the source metric.
        - alert: KafkaExporterUnderReplicatedPartition
          annotations:
            description: '{{`Topic {{ $labels.topic }} has {{ $value }} under-replicated partition {{ $labels.partition }}.`}}'
            summary: Topic has under-replicated partitions.
          expr: kafka_topic_partition_under_replicated_partition > 0
          for: 10s
          labels:
            area: platform
            severity: none
            team: atlas
        - alert: KafkaExporterTooLargeConsumerGroupLag
          annotations:
            description: '{{`Consumer group {{ $labels.consumergroup }} lag is too big ({{ $value }}) on topic {{ $labels.topic }}/partition {{ $labels.partition }}.`}}'
            summary: Consumer group lag is too big.
          expr: kafka_consumergroup_lag > 1000
          for: 10s
          labels:
            area: platform
            severity: none
            team: atlas
        - alert: KafkaExporterNoMessageForTooLong
          annotations:
            description: '{{`There are no messages in topic {{ $labels.topic }}/partition {{ $labels.partition }} for 10 minutes.`}}'
            summary: No message for 10 minutes.
          expr: changes(kafka_topic_partition_current_offset[10m]) == 0
          for: 10s
          labels:
            area: platform
            severity: none
            team: atlas
