apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: strimzi-entity-operator.rules
  namespace: {{ .Values.namespace  }}
spec:
  groups:
    - name: strimzi-entity-operator
      rules:
        - alert: StrimziTopicOperatorContainerDown
          annotations:
            description: Container topic-operator in Entity Operator pod has been down or in CrashLoopBackOff status for 3 minutes.
            summary: Container topic-operator in Entity Operator pod down or in CrashLoopBackOff status.
          expr: absent(container_last_seen{container="topic-operator",pod=~".+-entity-operator-.+"})
          for: 3m
          labels:
            area: platform
            severity: none
            team: atlas
            topic: kafka
        - alert: StrimziUserOperatorContainerDown
          annotations:
            description: Container user-operator in Entity Operator pod has been down or in CrashLoopBackOff status for 3 minutes.
            summary: Container user-operator in Entity Operator pod down or in CrashLoopBackOff status.
          expr: absent(container_last_seen{container="user-operator",pod=~".+-entity-operator-.+"})
          for: 3m
          labels:
            area: platform
            severity: none
            team: atlas
            topic: kafka
